#Default Config
#For the plugin to work, you must fill in the MYSLQ Database login info.
headsleaderboards: 
  enabled: false
  updateInterval: 30
  debugMode: false
database:
  hostname: localhost
  port: 3306
  database: database
  username: username
  password: password
leaderboards: ""
header:
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- '10'
- '11'
- '12'
- '13'
- '14'
- '15'
- '16'
- '17'
- '18'
- '19'
- '20'
- '21'
- '22'
- '23'
- '24'
- '25'
- '26'
- '27'
- '28'
- '29'
- '30'
- '31'
- '32'
- '33'
- '34'
- '35'
- '36'
- '37'
- '38'
- '39'
- '40'
- '41'
- '42'
- '43'
- '44'
- '45'
- '46'
- '47'
- '48'
- '49'
- '50'
