name: HeadLeaderBoards
main: com.headleaderboards.headleaderboards.HeadLeaderBoards
version: 2.1

commands:
   hlb:
      description: This is the main plugin command.
      usage: /<command> [args]
   hlbupdate:
      description: This command will update all leaderboards that are enabled.
      usage: /<command> [args]
permissions:
  hlb.*:
    description: Gives access to all HLB commands
    children:
      hlb.update: true
      hlb.signs: true
      hlb.commands: true
  hlb.update:
    description: Gives access to the hlbupdate command
    default: op
  hlb.signs:
    description: Allows the user to create and destroy hlb signs
    default: op
  hlb.commands:
    description: Give access to all other hlb commands
    default: op